"""
Deterministic Privacy Guard — SQL AST-Based PII Redaction.

Before any SQL generated by the Data Architect hits the DuckDB engine,
the Verifier uses this module to:
  1. Parse the SQL AST (Abstract Syntax Tree) using sqlglot.
  2. Identify "Sensitive" columns via a regex/dictionary based approach.
  3. Autonomously rewrite the query to inject hash() or mask() operations.

This proves Data Sovereignty and Privacy-by-Design for enterprise scale.
"""

from __future__ import annotations

import logging
import re
from typing import Any

import sqlglot
from sqlglot import exp

logger = logging.getLogger(__name__)


class PIIRedactor:
    """
    Deterministic Privacy Guard that analyzes and rewrites SQL queries
    at the AST level to protect Personally Identifiable Information (PII).
    """

    def __init__(
        self,
        sensitive_columns: list[str] | None = None,
        sensitive_patterns: list[str] | None = None,
        redaction_method: str = "hash",
    ) -> None:
        """
        Args:
            sensitive_columns: Exact column names to redact.
            sensitive_patterns: Regex patterns to identify sensitive column names.
            redaction_method: Function to wrap the column, e.g., 'hash' or 'mask'.
                              Since DuckDB has 'hash' and string functions, we default to 'hash'.
        """
        self.sensitive_columns = {
            col.lower() for col in (sensitive_columns or [
                "email", "phone", "cc_number", "ssn", "social_security",
                "credit_card", "password", "address"
            ])
        }

        default_patterns = [
            r".*_email$",
            r".*_phone$",
            r".*_ssn$",
            r"^pii_.*"
        ]
        self.sensitive_patterns = [
            re.compile(pattern, re.IGNORECASE)
            for pattern in (sensitive_patterns or default_patterns)
        ]

        self.redaction_method = redaction_method

    def _is_sensitive(self, col_name: str) -> bool:
        """Determine if a column name is considered sensitive."""
        col_lower = col_name.lower()
        if col_lower in self.sensitive_columns:
            return True

        for pattern in self.sensitive_patterns:
            if pattern.match(col_lower):
                return True
            
        return False

    def redact_sql(self, sql: str, dialect: str = "duckdb") -> tuple[str, list[str]]:
        """
        Parses the SQL, masks PII columns in SELECT clauses, and returns
        the rewritten SQL and a list of redacted columns.

        Returns:
            rewritten_sql (str): The safe SQL to run.
            redacted_cols (list[str]): Columns that were identified and masked.
        """
        try:
            ast = sqlglot.parse_one(sql, read=dialect)
        except Exception as e:
            logger.error("Failed to parse SQL AST for redaction: %s", e)
            # Fail closed on parsing failure to prevent PII leakage
            raise ValueError(f"Could not parse SQL safely: {e}")

        redacted_cols: set[str] = set()

        def transformer(node: exp.Expression) -> exp.Expression:
            # We specifically look for Column references
            if isinstance(node, exp.Column):
                col_name = node.name
                if self._is_sensitive(col_name):
                    redacted_cols.add(col_name)
                    # Create a function call: hash(column)
                    # Wait, if it's already wrapped in a hash, don't double wrap it.
                    # We can check parent
                    if isinstance(node.parent, exp.Func):
                        if node.parent.sql_name().lower() in ("hash", "md5", "mask"):
                            return node
                            
                    # Construct hash(node)
                    # By default DuckDB uses hash(), md5(), etc. We will use md5() as it returns varchar
                    func_name = "md5" if self.redaction_method == "hash" else self.redaction_method
                    
                    # Return the wrapped node
                    # We preserve the alias if it had one, but `transform` visits nodes bottom-up,
                    # the alias is usually on the parent `Alias` node in projection.
                    new_node = exp.func(func_name, node.copy())
                    return new_node
            return node

        rewritten_ast = ast.transform(transformer)
        rewritten_sql = rewritten_ast.sql(dialect=dialect)
        
        if redacted_cols:
            logger.info("PII Redactor masked columns: %s", ", ".join(redacted_cols))
            
        return rewritten_sql, list(redacted_cols)
